# Generated by Django 5.2 on 2025-04-16 11:46

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=core.utils.generate_id,
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("role", models.CharField(max_length=255)),
                ("message", models.TextField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
